# Generated by Django 6.0.2 on 2026-02-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('horimetro', models.PositiveIntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='MedicacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.medicacao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_telemetria.veiculo')),
            ],
        ),
    ]
